language: python
python:
  - '3.7'
install:
  - 'pip install -r obs/api/requirements.txt'
  - 'pip install -r requirements-dev.txt'
  - 'pip install -e .'
script:
  - 'black --check .'
  - 'pytest -vv -s'
